name: Lint

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run linting checks
        uses: docker://cdssnc/tf-lint-github-action
        args: --fast
