name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: sudo npm i -g standard-version
      - name: Configure GitHub
        run: |
          git config --global user.name ${{secrets.GITHUB_USER}}
          git config --global user.email ${{secrets.GITHUB_EMAIL}}
      - name: Release
        run: sudo standard-version
      - name: Push changes
        run: sudo git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
