name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: sudo npm i -g standard-version
      - name: Release
        run: standard-version
      - name: Push changes
        run: git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
